/**
 * Color Schemes for Poster Generation
 * Contains all available color schemes for golf course posters
 */

const whiteColors = {
  backgroundColor: "#ffffff",
  textColor: "#000000",
  outlineColorInner: "#9a9a9a",
  outlineColorOuter: "#000000",
  compassColor: "#888888",
  scoreCardColor: "#000000",
  fairway: "#758838",
  fairwayOutline: "#525d29",
  background: "#ffffff",
  water: "#CFD9DA",
  sand: "#F3EE95",
  sandOutline: "#aaa464",
  green: "#a6ad4c",
  greenOutline: "#f5ec99",
  tee: "#758838",
  teeOutline: "#525d29",
  lines: "#991B1E",
  number: "#991B1E",
  numberContainer: "#ffffff",
  numberContainerOutline: "#991B1E",
  clubHouse: "#4e4e4e",
  signature: "#000000",
  extraTitle: "#9a7e2e",
  wasteLand: "#edece3",
};

const blueColors = {
  backgroundColor: "#E6EAEF",
  textColor: "#1F4A70",
  outlineColorInner: "#7086a6",
  outlineColorOuter: "#1F4A70",
  compassColor: "#1F4A70",
  scoreCardColor: "#1F4A70",
  fairway: "#1F4A70",
  fairwayOutline: "#0f2d4a",
  background: "#5fa8d3",
  water: "#7086A6",
  sand: "#FFFFFF",
  sandOutline: "#e6e6e6",
  green: "#FFFFFF",
  greenOutline: "#e6e6e6",
  tee: "#1F4A70",
  teeOutline: "#0f2d4a",
  lines: "#ffffff",
  number: "#1a2b40",
  numberContainer: "#ffffff",
  numberContainerOutline: "#1a2b40",
  clubHouse: "#4e4e4e",
  signature: "#ffffff",
  extraTitle: "#9a7e2e",
  wasteLand: "#edece3",
};

const greenColors = {
  backgroundColor: "#D5EAD3",
  textColor: "#316E36",
  outlineColorInner: "#80b087",
  outlineColorOuter: "#316E36",
  compassColor: "#316E36",
  scoreCardColor: "#316E36",
  fairway: "#316E36",
  fairwayOutline: "#1f4a23",
  background: "#5fa8d3",
  water: "#80B087",
  sand: "#D5EAD3",
  sandOutline: "#316E36",
  green: "#FFFFFF",
  greenOutline: "#e6e6e6",
  tee: "#2c537d",
  teeOutline: "#1a2b40",
  lines: "#ffffff",
  number: "#1a2b40",
  numberContainer: "#ffffff",
  numberContainerOutline: "#1a2b40",
  clubHouse: "#4e4e4e",
  signature: "#ffffff",
  extraTitle: "#9a7e2e",
  wasteLand: "#edece3",
};

const navyColors = {
  backgroundColor: "#7086A6",
  textColor: "#FFFFFF",
  outlineColorInner: "#9a9a9a",
  outlineColorOuter: "#000000",
  compassColor: "#FFFFFF",
  scoreCardColor: "#FFFFFF",
  fairway: "#4D4E4E",
  fairwayOutline: "#2a2a2a",
  background: "#5fa8d3",
  water: "#9B9B9B",
  sand: "#9B9B9B",
  sandOutline: "#7a7a7a",
  green: "#FFFFFF",
  greenOutline: "#e6e6e6",
  tee: "#4D4E4E",
  teeOutline: "#2a2a2a",
  lines: "#ffffff",
  number: "#1a2b40",
  numberContainer: "#ffffff",
  numberContainerOutline: "#1a2b40",
  clubHouse: "#4e4e4e",
  signature: "#ffffff",
  extraTitle: "#9a7e2e",
  wasteLand: "#edece3",
};

const brownColors = {
  backgroundColor: "#B4B3A8",
  textColor: "#FFFFFF",
  outlineColorInner: "#9a9a9a",
  outlineColorOuter: "#231F20",
  compassColor: "#FFFFFF",
  scoreCardColor: "#FFFFFF",
  fairway: "#4D4E4E",
  fairwayOutline: "#2a2a2a",
  background: "#5fa8d3",
  water: "#9B9B9B",
  sand: "#9B9B9B",
  sandOutline: "#7a7a7a",
  green: "#FFFFFF",
  greenOutline: "#e6e6e6",
  tee: "#4D4E4E",
  teeOutline: "#2a2a2a",
  lines: "#ffffff",
  number: "#1a2b40",
  numberContainer: "#ffffff",
  numberContainerOutline: "#1a2b40",
  clubHouse: "#4e4e4e",
  signature: "#ffffff",
  extraTitle: "#9a7e2e",
  wasteLand: "#edece3",
};

const colorSchemes = {
  White: whiteColors,
  Navy: navyColors,
  Green: greenColors,
  Blue: blueColors,
  Brown: brownColors,
};

module.exports = {
  whiteColors,
  blueColors,
  greenColors,
  navyColors,
  brownColors,
  colorSchemes,
};
